Taller buttons
HBTGmbH/salat pull request #196
Opened 2022-09-28 11:46 UTC by youseeus

2022-09-29 09:46 UTC, sjthiessen commented
Ich schau mir grad noch an ob ich 1-2 Icons mehr aktualisieren kann (z.B. für die Massenbearbeitung)

2022-09-30 10:51 UTC, sjthiessen commented
Done: https://github.com/HBTGmbH/salat/pull/199

2022-09-30 15:52 UTC, KlausRicharz commented on src/main/java/org/tb/common/DateTimeViewHelper.java
> -    if (index == -1) { // st might already be in its correct form
Reines Code-Formatter-Thema? Bitte prüfen.

2022-09-30 15:56 UTC, KlausRicharz requested changes
chart.js scheint ausversehen reingerutscht zu sein. Hierfür bitte auch webjars verwenden (siehe pom.xml).

2022-09-30 15:56 UTC, KlausRicharz commented on src/main/webapp/scripts/chart.js
> +/*!
Ausversehen committed?

2022-09-30 15:56 UTC, KlausRicharz commented on src/main/java/org/tb/common/DateTimeViewHelper.java
> -    if (index == -1) { // st might already be in its correct form
Reines Code-Formatter-Thema? Bitte prüfen.

2022-09-30 16:07 UTC, KlausRicharz commented on src/main/java/org/tb/common/DateTimeViewHelper.java
> -    if (index == -1) { // st might already be in its correct form
code formatting müssen wir mal generell checken - postponed

2022-09-30 16:09 UTC, KlausRicharz commented on src/main/java/org/tb/common/DateTimeViewHelper.java
> -    if (index == -1) { // st might already be in its correct form
Postponed, see #200 #201 #202

2022-09-30 16:09 UTC, KlausRicharz commented on src/main/webapp/scripts/chart.js
> +/*!
werde ich wieder löschen

2022-09-30 16:09 UTC, KlausRicharz approved these changes

2022-09-30 16:09 UTC, merged