Feature/bootstrap calendar
HBTGmbH/salat pull request #197
Opened 2022-09-28 16:12 UTC by youseeus

#186 Layout Datepicker verbessern

2022-09-29 09:42 UTC, sjthiessen commented
Ich schau mir grad noch an ob ich 1-2 Icons mehr aktualisieren kann (z.B. für die Massenbearbeitung)

2022-09-30 16:00 UTC, KlausRicharz requested changes
Es scheint so, als ob dieser PR auch die Änderungen aus https://github.com/HBTGmbH/salat/pull/196 enthält. Soll das so?

2022-09-30 16:10 UTC, KlausRicharz commented on src/main/java/org/tb/common/DateTimeViewHelper.java
> -    if (index == -1) { // st might already be in its correct form
postponed

2022-09-30 16:10 UTC, KlausRicharz approved these changes

2022-09-30 16:13 UTC, merged