#446 CSV import in matrix overview
HBTGmbH/salat pull request #449
Opened 2024-11-14 21:26 UTC by hehu80

2024-11-15 07:55 UTC, KlausRicharz reviewed
Maybe better store timereports in a single call to timereport service

2024-11-15 07:55 UTC, KlausRicharz commented on src/main/java/org/tb/dailyreport/service/DailyWorkingReportService.java
Evaluate upsert, maybe deletion is too rigorous

2024-11-16 16:20 UTC, KlausRicharz commented on src/main/java/org/tb/dailyreport/service/DailyWorkingReportService.java
what about other bookings that are not part of your project. so maybe better to delete only those that are matching the orders in the file?

2024-11-17 10:35 UTC, hehu80 commented on src/main/java/org/tb/dailyreport/service/DailyWorkingReportService.java
Or we let the user decide if he wants to keep existing bookings or not: 
![Screenshot 2024-11-17 at 11-35-01 SALAT - Matrixübersicht](https://github.com/user-attachments/assets/fddd4e1d-255a-488b-821d-1386be1a6c83)

2024-11-18 12:50 UTC, KlausRicharz requested changes
see comments

2024-11-18 12:50 UTC, KlausRicharz commented on src/main/java/org/tb/dailyreport/action/ShowMatrixAction.java
> +        if(task == null && reportForm.getImportFile() != null) {
Should we introduce a specific task "importCsv"?

2024-11-18 12:50 UTC, KlausRicharz commented on src/main/java/org/tb/dailyreport/rest/DailyReportData.java
> +        return toBuilder().id(0).build();
0 = special case?

2024-11-18 12:50 UTC, KlausRicharz commented on src/main/java/org/tb/dailyreport/service/DailyWorkingReportService.java
> +        workingDay.setEmployeecontract(employeecontract);
Das ist nur bei neuen Working Days wichtig

2024-11-18 12:50 UTC, KlausRicharz commented on src/main/java/org/tb/dailyreport/service/DailyWorkingReportService.java
> +            throw new ResponseStatusException(NOT_FOUND, "Could not find employeeorder with id " + employeeOrderId);
ResponseStatusException nicht im Service verwenden, besser InvalidDataException.

2024-11-18 12:50 UTC, KlausRicharz commented on src/main/java/org/tb/dailyreport/service/DailyWorkingReportService.java
> +            throw new ResponseStatusException(NOT_FOUND, "Could not find employeecontract for order with id " + employeeOrderId);
same -> InvalidDataException

2024-11-19 07:12 UTC, KlausRicharz approved these changes

2024-11-19 07:30 UTC, merged